<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="AddClass.aspx.cs" Inherits="AddClass" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style1
        {
            width: 755px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table class="tbl">
        <tr>
            <td class="tblhead">
                ADD New Class</td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
        </tr>
        <tr>
            <td>
                <table align="center" class="style1">
                    <tr>
                        <td class="lbl">
                            Class Name :
                        </td>
                        <td>
                            <asp:TextBox ID="txtclass" runat="server" CssClass="txt"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" 
                                ControlToValidate="txtclass" ErrorMessage="**" ForeColor="Red" 
                                SetFocusOnError="True"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="lbl">
                            Basic Pay :</td>
                        <td>
                            <asp:TextBox ID="txtbpay" runat="server" CssClass="txt"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" 
                                ControlToValidate="txtbpay" ErrorMessage="**" ForeColor="Red" 
                                SetFocusOnError="True"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="lbl">
                            Salary :
                        </td>
                        <td>
                            <asp:TextBox ID="txtsalary" runat="server" CssClass="txt"></asp:TextBox>
                            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" 
                                ControlToValidate="txtsalary" ErrorMessage="**" ForeColor="Red" 
                                SetFocusOnError="True"></asp:RequiredFieldValidator>
                        </td>
                    </tr>
                    <tr>
                        <td class="lbl">
                            TravelAllowance :
                        </td>
                        <td>
                            <asp:TextBox ID="txttall" runat="server" placeholder="0" CssClass="txt"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td class="lbl">
                            MedicalAllowance :
                        </td>
                        <td>
                            <asp:TextBox ID="txtmall" runat="server" placeholder="0" CssClass="txt"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td class="lbl">
                            WashingAllowance :
                        </td>
                        <td>
                            <asp:TextBox ID="txtwall" runat="server" placeholder="0" CssClass="txt"></asp:TextBox>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;</td>
                        <td>
                            <asp:Button ID="btnadd" runat="server" CssClass="btn" onclick="btnadd_Click" 
                                Text="ADD Class" Width="90px" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;</td>
                        <td>
                            <asp:Label ID="Label1" runat="server"></asp:Label>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;</td>
                        <td style="text-align: left">
                            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
                                CellPadding="4" ForeColor="Black" GridLines="Vertical" 
                                AutoGenerateColumns="False" DataKeyNames="cid" 
                                onrowdeleting="GridView1_RowDeleting" Width="600px" BackColor="White" 
                                BorderColor="#FFCCFF" BorderStyle="Solid" BorderWidth="1px">
                                <AlternatingRowStyle BackColor="White" />
                                <FooterStyle BackColor="#CCCC99" />
                                <HeaderStyle BackColor="#FFCCFF" Font-Bold="True" ForeColor="#006600" />
                                <PagerStyle BackColor="#F7F7DE" ForeColor="Black" HorizontalAlign="Right" />
                                <RowStyle BackColor="#F7F7DE" />
                                <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />
                                <SortedAscendingCellStyle BackColor="#FBFBF2" />
                                <SortedAscendingHeaderStyle BackColor="#848384" />
                                <SortedDescendingCellStyle BackColor="#EAEAD3" />
                                <SortedDescendingHeaderStyle BackColor="#575357" />
                                <Columns>
                                <asp:BoundField HeaderText="Class" DataField="class" />
                                <asp:BoundField HeaderText="Basic Pay" DataField="basicpay" />
                                <asp:BoundField HeaderText="Salary" DataField="salary" />
                                 <asp:BoundField HeaderText="T_ALL" DataField="TravelAllowance" />
                                  <asp:BoundField HeaderText="M_ALL" DataField="MedicalAllowance" />
                                   <asp:BoundField HeaderText="W_ALL" DataField="WashingAllowance" />
                                </Columns>
                            </asp:GridView>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td>
                &nbsp;</td>
        </tr>
    </table>
</asp:Content>

